"""initial schema

Revision ID: 8e6c2d089ee8
Revises:
Create Date: 2026-09-27 18:36:16.004402+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8e6c2d089ee8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credentials",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("openbao_path", sa.Text(), nullable=False),
        sa.Column("openbao_key", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "type IN ('ssh_key', 'vault_password', 'git_token')", name=op.f("ck_credentials_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credentials")),
        sa.UniqueConstraint("name", name=op.f("uq_credentials_name")),
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("git_url", sa.Text(), nullable=False),
        sa.Column("branch", sa.Text(), nullable=False),
        sa.Column("credential_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["credentials.id"],
            name=op.f("fk_projects_credential_id_credentials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("name", name=op.f("uq_projects_name")),
    )
    op.create_table(
        "inventories",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=True),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "(source_type = 'project_file' AND path IS NOT NULL AND project_id IS NOT NULL) OR (source_type = 'inline' AND content IS NOT NULL)",
            name=op.f("ck_inventories_source_fields"),
        ),
        sa.CheckConstraint(
            "source_type IN ('project_file', 'inline')", name=op.f("ck_inventories_source_type")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_inventories_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventories")),
        sa.UniqueConstraint("name", name=op.f("uq_inventories_name")),
    )
    op.create_table(
        "templates",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("playbook_path", sa.Text(), nullable=False),
        sa.Column("inventory_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "extra_vars",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("limit", sa.Text(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("skip_tags", sa.Text(), nullable=True),
        sa.Column("verbosity", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("machine_credential_id", sa.BigInteger(), nullable=False),
        sa.Column("vault_credential_id", sa.BigInteger(), nullable=True),
        sa.Column("timeout_s", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "timeout_s IS NULL OR timeout_s > 0", name=op.f("ck_templates_timeout_s")
        ),
        sa.CheckConstraint("verbosity BETWEEN 0 AND 5", name=op.f("ck_templates_verbosity")),
        sa.ForeignKeyConstraint(
            ["inventory_id"], ["inventories.id"], name=op.f("fk_templates_inventory_id_inventories")
        ),
        sa.ForeignKeyConstraint(
            ["machine_credential_id"],
            ["credentials.id"],
            name=op.f("fk_templates_machine_credential_id_credentials"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_templates_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["vault_credential_id"],
            ["credentials.id"],
            name=op.f("fk_templates_vault_credential_id_credentials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
        sa.UniqueConstraint("name", name=op.f("uq_templates_name")),
    )
    op.create_table(
        "runs",
        sa.Column("template_id", sa.BigInteger(), nullable=False),
        sa.Column("triggered_by", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column(
            "extra_vars",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("limit", sa.Text(), nullable=True),
        sa.Column("commit_sha", sa.Text(), nullable=True),
        sa.Column("worker_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rc", sa.BigInteger(), nullable=True),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'successful', 'failed', 'error', 'timeout', 'canceled', 'skipped')",
            name=op.f("ck_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"], ["templates.id"], name=op.f("fk_runs_template_id_templates")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index("ix_runs_status_created_at", "runs", ["status", "created_at"], unique=False)
    op.create_index(
        "ix_runs_template_id_created_at", "runs", ["template_id", "created_at"], unique=False
    )
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("event", sa.Text(), nullable=False),
        sa.Column("host", sa.Text(), nullable=True),
        sa.Column("task", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column(
            "data", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
        sa.UniqueConstraint("run_id", "seq", name="uq_run_events_run_id_seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_events")
    op.drop_index("ix_runs_template_id_created_at", table_name="runs")
    op.drop_index("ix_runs_status_created_at", table_name="runs")
    op.drop_table("runs")
    op.drop_table("templates")
    op.drop_table("inventories")
    op.drop_table("projects")
    op.drop_table("credentials")
    # ### end Alembic commands ###
