"""maintenance status

Revision ID: 3734d2651b98
Revises: 16d949879b7e
Create Date: 2026-09-28 19:18:03.833944+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3734d2651b98"
down_revision: str | None = "16d949879b7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_status",
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_status", sa.Text(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.CheckConstraint(
            "last_status IN ('ok', 'failed')", name=op.f("ck_maintenance_status_last_status")
        ),
        sa.PrimaryKeyConstraint("task", name=op.f("pk_maintenance_status")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("maintenance_status")
    # ### end Alembic commands ###
